{% set name = "requests_download" %}
{% set version = "0.1.2" %}
{% set wheel_tag = "py2.py3-none-any" %}
{% set fn = "{}-{}-{}.whl".format(name, version, wheel_tag) %}
{% set sha256 = "994d9d332befae6616f562769bab163f08d6404dc7e28fb7bfed4a0a43a754ad" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://pypi.io/packages/py2.py3/{{ name[0] }}/{{ name }}/{{ fn }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: pip install --no-deps {{ fn }}
  skip: True  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests

test:
  imports:
    - requests_download

about:
  home: https://github.com/takluyver/requests_download
  license: MIT
  summary: Download files using requests and save them to a target path

extra:
  recipe-maintainers:
    - Carreau
    - minrk
    - takluyver
